### ISSUE TITLE
Using managed_objects = False does not update files

### ISSUE THREAD

**Issue by inboxedshoe** [pulumi/pulumi-synced-folder#26] opened 2023-04-18 19:37 UTC
### What happened?

Added the managed_objects=False flag when creating a google cloud-synced folder, the files were pushed at the first pulumi run but never updated after (pulumi up always says 0 changes). I now have to manually call rsync everytime.

### Expected Behavior

Pulumi automatically uses rsync to sync the files

### Steps to reproduce

Set managed_objects=False

### Output of `pulumi about`

CLI
Version      3.63.0
Go Version   go1.20.2
Go Compiler  gc

Plugins
NAME           VERSION
gcp            6.53.0
python         unknown
synced-folder  0.10.2

Host
OS       ubuntu
Version  22.04
Arch     x86_64

This project is written in python: executable='/usr/bin/python3' version='3.10.6
'

Current Stack: inboxedshoe/hugo_git/dev

TYPE                                                   URN
pulumi:pulumi:Stack                                    urn:pulumi:dev::hugo_git::pulumi:pulumi:Stack::hugo_git-dev
pulumi:providers:gcp                                   urn:pulumi:dev::hugo_git::pulumi:providers:gcp::default_6_53_0
gcp:compute/globalAddress:GlobalAddress                urn:pulumi:dev::hugo_git::gcp:compute/globalAddress:GlobalAddress::ip
gcp:storage/bucket:Bucket                              urn:pulumi:dev::hugo_git::gcp:storage/bucket:Bucket::hugo_site_bucket
gcp:storage/bucketIAMBinding:BucketIAMBinding          urn:pulumi:dev::hugo_git::gcp:storage/bucketIAMBinding:BucketIAMBinding::bucket-iam-binding
gcp:compute/backendBucket:BackendBucket                urn:pulumi:dev::hugo_git::gcp:compute/backendBucket:BackendBucket::backend-bucket
pulumi:providers:synced-folder                         urn:pulumi:dev::hugo_git::pulumi:providers:synced-folder::default_0_10_2
gcp:compute/uRLMap:URLMap                              urn:pulumi:dev::hugo_git::gcp:compute/uRLMap:URLMap::url-map
gcp:compute/targetHttpProxy:TargetHttpProxy            urn:pulumi:dev::hugo_git::gcp:compute/targetHttpProxy:TargetHttpProxy::http-proxy
gcp:compute/globalForwardingRule:GlobalForwardingRule  urn:pulumi:dev::hugo_git::gcp:compute/globalForwardingRule:GlobalForwardingRule::http-forwarding-rule
synced-folder:index:GoogleCloudFolder                  urn:pulumi:dev::hugo_git::synced-folder:index:GoogleCloudFolder::synced-folder
pulumi:providers:command                               urn:pulumi:dev::hugo_git::pulumi:providers:command::default_0_7_0
command:local:Command                                  urn:pulumi:dev::hugo_git::synced-folder:index:GoogleCloudFolder$command:local:Command::synced-folder-sync-command

Found no pending operations associated with dev

Backend
Name           pulumi.com
URL            https://app.pulumi.com/inboxedshoe
User           inboxedshoe
Organizations  inboxedshoe, EpicGames

Dependencies:
NAME                  VERSION
pip                   23.0.1
pulumi-gcp            6.53.0
pulumi-synced-folder  0.10.2
setuptools            67.6.1
wheel                 0.40.0

Pulumi locates its logs in /tmp by default

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by cnunciato** [comment] 2023-07-23 22:20
Duplicate of #27.

**Closed by cnunciato** 2023-07-23 22:20 UTC
Labels: kind/bug, resolution/duplicate
